### PR TITLE
add tutorial notebook for kraken use

### PR DESCRIPTION
**Pull request by John-Ragland**
I created a tutorial notebook for using the kraken functionality, that I though might be useful to others.
(I also added .DS_store (a file created by macOS) to the .gitignore)

Let me know what you think!

### CODE REVIEW

**Comment by stephenpcook** [comment]
IMO the ignore `.DS_store` should probably just go in your [global ignore file](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) (or a `.git/info/exclude`).

**Comment by John-Ragland** [comment]
That's a great point, I've configured my local environment and have removed this from the .gitignore

**Comment by hunterakins** [comment]
For some reason the pull didn't grab the tutorial folder and file...not sure why. Maybe try pulling some new commits I just pushed and merging, and I'll try and pull again? Or any better ideas you may have. I'm a git noob.

**Comment by hunterakins** [comment]
Thank you very much John, I appreciate the work you've done.

**Comment by John-Ragland** [comment]
I think the problem is that I accidentally included this notebook in the NMESH branch and then deleted it in that branch. I think the easiest way to fix this is for me to just create a separate pull request. Thank!

**Comment by hunterakins** [comment]
Okay great thanks I will merge when you create it

**Pull request merged**
